# Generated by Django 3.2 on 2021-05-21 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('translation', models.TextField()),
                ('status', models.DateTimeField(auto_now_add=True)),
                ('colour_status', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('orange', 'orange')], default='red', max_length=6)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StartPage.book')),
            ],
        ),
    ]
